CREATE TABLE IF NOT EXISTS entregadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    codigo_acesso TEXT
);

CREATE TABLE IF NOT EXISTS rotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_rota DATE NOT NULL,
    entregador TEXT NOT NULL,
    entregador_id BIGINT REFERENCES entregadores(id),
    veiculo TEXT,
    observacao TEXT,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS entregas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rota_id BIGINT NOT NULL REFERENCES rotas(id) ON DELETE CASCADE,
    venda_id TEXT,
    numero_venda TEXT,
    cliente TEXT NOT NULL,
    telefone TEXT,
    endereco TEXT NOT NULL,
    cidade TEXT,
    estado TEXT,
    cep TEXT,
    status TEXT NOT NULL DEFAULT 'PENDENTE',
    recebido_por TEXT,
    observacao TEXT,
    data_entrega TIMESTAMPTZ,
    atualizado_por TEXT,
    api_retorno TEXT,
    origem_pedido TEXT,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ocorrencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrega_id BIGINT NOT NULL REFERENCES entregas(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL,
    descricao TEXT,
    data_ocorrencia TIMESTAMPTZ DEFAULT NOW(),
    usuario TEXT
);

CREATE INDEX IF NOT EXISTS idx_entregas_status ON entregas(status);
CREATE INDEX IF NOT EXISTS idx_entregas_rota_id ON entregas(rota_id);
CREATE INDEX IF NOT EXISTS idx_rotas_data ON rotas(data_rota);
CREATE INDEX IF NOT EXISTS idx_ocorrencias_entrega ON ocorrencias(entrega_id);
